version: '3.3'
services:
  database:
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3030:3306"
  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - './apps/hola/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '8090:80'
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file: ./apps/hola/.env